apiVersion: v1
kind: Service
metadata:
  name: nlb-nagp-postgres
  labels:
    app: nagp-postgres
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: nagp-postgres     
  ports:
  - port: 8081
    targetPort: 8081